### ISSUE TITLE
Incorrect usage of call

### ISSUE THREAD

**Issue by hueniverse** [delvedor/router-benchmark#4]
**call** methods must be lowercase when performing a lookup. Your numbers for **call** are all wrong because you are measuring the time it takes to lookup + generate a boom error. Changing it to `get` makes a huge difference...

**Comment by delvedor** [comment]
Hi! Thank you for checking out this!
I'll update the script asap, have you got any other suggestion? :)

**Comment by hueniverse** [comment]
Great. You've seen my other issues. Once those are resolved I'll play with this some more.

**Comment by delvedor** [comment]
Hi!
This should be fixed in https://github.com/delvedor/router-benchmark/commit/a053c70833caf73b443f52f435a4ce4e7215d9ce, please confirm.
I'll investigate on the others issues as soon as I have time :)

**Comment by hueniverse** [comment]
Looks good. Would love to see new numbers posted. Thanks.

**Comment by delvedor** [comment]
I've updated the benchmarks, I'm also working on a new script to have a more real-world benchmark :)
